version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: biblioteca-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: biblioteca_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - biblioteca-network

volumes:
  postgres_data:

networks:
  biblioteca-network:
    driver: bridge
